---
- name: Install AT Job
  hosts: all

  tasks:
  - name: at command needs to be installed
    yum:
      name: at
      state: present

  - name: Schedule a command to execute in 20 minutes as root
    junipernetworks.junos.junos_interfaces:
      running_config: 