---
- name: 
  hosts: AU350CSM-S-8-1
  connection: local
  gather_facts: no

  tasks:


# Refers to: https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_interfaces_module.html 
# Need to assign a VLAN, and set a description.

- name: "Assign VLAN to Office 6 South - Level 8"
  juniper.junos.junos_l2_interfaces:
    config:
    - name: ge-0/0/18 #WS010  Office 6S
      access:
        vlan: vlan.0090
    - name: ge-0/0/20 #WS011  Office 6S
      access:
        vlan: vlan.0090
    - name: ge-0/0/26  #WS014 Office 6S
      access:
        vlan: vlan.0090
    - name: ge-0/0/28  #WS015  Office 6S
      access:
        vlan: vlan.0090
    state: replaced


- name: Merge provided configuration with device configuration (default operation is merge)
  juniper.junos.junos_interfaces:
    config:
    - name: ge-0/0/18
      description: "WS010 - Level 8 South - Office 6S - CSC"
    - name: ge-0/0/20
      description: "WS011 - Level 8 South - Office 6S - CSC"
    - name: ge-0/0/26
      description: "WS014 - Level 8 South - Office 6S - CSC"
    - name: ge-0/0/28
      description: "WS015 - Level 8 South - Office 6S - CSC"
    state: merged



#- name: "Delete L2 attributes of given interfaces (Note: This won't delete the interface itself)."
#  junipernetworks.junos.junos_l2_interfaces:
#    config:
#    - name: ge-0/0/1
#    - name: ge-0/0/2
#    - name: ge-1/0/45
#    - name: ge-1/0/47
#    - name: ge-2/0/2
#    - name: ge-2/0/4
#    - name: ge-2/0/6
#    - name: ge-2/0/8
#    - name: ge-2/0/10
#    - name: ge-2/0/12
#    - name: ge-2/0/14
#    - name: ge-2/0/16
#    - name: ge-2/0/18
#    - name: ge-2/0/20
#    - name: ge-2/0/30
#    - name: ge-2/0/32
#    state: deleted


###  This code works, but the config file formatting isn't right 
#   - name: L2
#     junipernetworks.junos.junos_l2_interfaces:
#       config:
#        - name: ge-0/0/1
#          access:
#            vlan: vlan.0002
#        - name: ge-0/0/2
#          access:
#            vlan: vlan.0003
#      state: replaced